### ISSUE TITLE
繁體簡碼

### ISSUE THREAD

**Issue by ywxt** [forFudan/xuma#1]
碼表有繁體簡碼版本嗎？看了下，簡碼好像是簡體版本，詞組也都是簡體的。

看到作者也是使用繁體的，有點疑惑。

**Comment by forFudan** [comment]
> 碼表有繁體簡碼版本嗎？看了下，簡碼好像是簡體版本，詞組也都是簡體的。
> 
> 看到作者也是使用繁體的，有點疑惑。

的確是有一套繁體的簡碼，是按照大陸古籍標準設定的，詞庫較小。

**Comment by ywxt** [comment]
既然是大陸古籍標準，那還是我自己安排簡碼吧。

本來想着白嫖的🤣

**Comment by forFudan** [comment]
> 既然是大陸古籍標準，那還是我自己安排簡碼吧。
> 
> 本來想着白嫖的🤣

哈哈，差距的確不小。還是自己排順手。
