### ISSUE TITLE
丟失的拆分與錯碼

### ISSUE THREAD

**Issue by ywxt** [forFudan/xuma#2]
康熙部首中的拆分應該都沒有，而且Less Z方案這部分的編碼沒有更新，也就是說康熙部首這部分存在很多錯碼。

**Comment by forFudan** [comment]
> 康熙部首中的拆分應該都沒有，而且Less Z方案這部分的編碼沒有更新，也就是說康熙部首這部分存在很多錯碼。

没錯，拆分是在進行的。目前還有四千箇要校準。徐碼群裏今天討論過，這部分需要時間。

**Comment by ywxt** [comment]
感謝回覆，作者辛苦了。

**Comment by ywxt** [comment]
感謝回覆，作者辛苦了。

**Comment by forFudan** [comment]
> 感謝回覆，作者辛苦了。

不謝！你弄虎碼和山人也辛苦了。
