### ISSUE TITLE
因 unicode 更改字形出现的错码

### ISSUE THREAD

**Issue by j1g5awi** [forFudan/xuma#5]
|字|当前拆分|正確拆分|
|-|-|-|
|濹 |氵日土灬土 | 氵黑土|
|褝|衤𭕄日十| 衤丷日十|
|肞|月丶乂| 月又丶|
|䕎|艹目口田|艹日口田|

**Comment by forFudan** [comment]
已經修正了。
https://github.com/forFudan/xuma/commit/efd866fc108ed196f1028b328d896de646452c64
