### ISSUE TITLE
字符過濾脚本無效

### ISSUE THREAD

**Issue by j1g5awi** [forFudan/xuma#6]
lua 以下两处写死了 `yuhao_char_*`，但方案的开关仍为 `forfudan_freq_*`，脚本读不到开关配置

https://github.com/forFudan/xuma/blob/d36f6d73baea8b2347b789333012788f85ad1c49/schema/lua/yuhao_char_filter.lua#L66

https://github.com/forFudan/xuma/blob/d36f6d73baea8b2347b789333012788f85ad1c49/schema/lua/yuhao_char_filter.lua#L83

**Comment by forFudan** [comment]
已經修正了。
efd866f
